### ISSUE TITLE
Problems with keys without values in URL

### ISSUE THREAD

**Issue by clente** [auth0/auth0.js#1038]
### Description

While working on an R interface to Auth0's SDK, I've bumped into a query string parsing problem. R's [Shiny](https://github.com/rstudio/shiny) package can take parameters of the form `url/?_inputs_&n=200` but, if this is forwarded to the `redirectUri` parameter, it redirects the user to `url/?_inputs_=&n=200` (which doesn't work).

### Prerequisites

[X] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

[X] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

[X] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

[X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

[X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Using auth0.js v9 on Firefox 69.0 in Manjaro Linux 18.0.4

**Comment by luisrudge** [comment]
Can you please share a simple snippet on how you're sending this param?

Also, the redirectUri should be a fixed url because you'll have to whitelist it in the Dashboard. Are the params after the query string being updated by the user? If yes, then that won't work either because the redirectUri won't be whitelisted and the server will reject the authentication request.
