### ISSUE TITLE
`renewAuth` cannot validate `state` param on Chrome 80 when iframed

### ISSUE THREAD

**Issue by smaclell** [auth0/auth0.js#1077]
### Description

In Chrome 80 there have been a number of changes to cookies within the context of 3rd party sites. A portion of our application is iframed within 3rd party applications and is not able to renew authentication.

We believe our workflow is silently failing to save cookies, potentially due to not having SameSite set correctly.

We are calling `renewAuth` against our OAuth provider. Internally, it generates a unique state and tries to save it to a cookie. The callback fails with the following error:

![The error as reproduced by the code below](https://user-images.githubusercontent.com/103917/73460597-c465d080-4346-11ea-8f7b-551261fa4cf3.png)

Instead we are expecting the callback to succeed have have a valid token. The token is sent back from our OAuth provider with a valid state.

Does the code need to reload the saved cookie to validate the hash? It looks like it could generate the valid state and then compare against the response directly instead of reloading the transaction.

We would be happy to contribute a pull request to address the issue however you would like. Thank you for the wonderful library.

### Reproduction

Our code is roughly this:

```
const auth = new auth0.WebAuth({
  domain: `ourdomain.com`,
  clientID: 'ignore',
  scope: 'email',
  audience: 'ignored',
  responseType: 'token',
  _sendTelemetry: false,
});

const params = {
  redirectUri: 'https://ourdomain.com/v1/silent.html',
  clientID: 'test-client',
  usePostMessage: true,
  postMessageOrigin: 'ourdomain.com',
  postMessageDataType: 'silent',
};

return new Promise((resolve, reject) => {
  auth.renewAuth(
    params,
    (error, result) => {
      if (error || !result) {
        console.error('silent fail', error);
        return reject(error);
      }

      const { accessToken, expiresIn } = result;

      if (!accessToken || !expiresIn) {
        return reject(new Error('Expected accessToken and expiresIn from silent response'));
      }

      this.accessToken = accessToken;
      console.log(`Silently authed for ${expiresIn} seconds`);
      return resolve();
    },
  );
});
```

Within `renewAuth`, sets the `state` parameter` when it calls:

Source: https://github.com/auth0/auth0.js/blob/v9.11.3/src/web-auth/index.js#L476

```
params = this.transactionManager.process(params);
```

However, within `validateAuthenticationResponse` it tries to read the state from the cookie again, but fails since it was not saved.

The `parseHash` call is here: https://github.com/auth0/auth0.js/blob/v9.11.3/src/web-auth/index.js#L506
The `state` is validated here: https://github.com/auth0/auth0.js/blob/v9.11.3/src/web-auth/index.js#L288

We have added `__tryLocalStorageFirst: true` to the `WebAuth` setup to temporarily work around this issue.

### Environment

- 9.11.3 (The code has not been updated in the latest version)
- Chrome 80 on a MacOS 10.14.5

**Comment by stevehobbsdev** [comment]
Hi @smaclell, apologies for the delay on this.

> Does the code need to reload the saved cookie to validate the hash?

Yes, the state is generated before authorization, saved and then retrieved again post-authorization in order to validate it. The state value is non-deterministic and so the only way to valiadate it is to persist it.

Couple of questions:

* Do the parts of your app that are not served in an iframe manage to validate state OK, or it that not something you can reasonably test?
* Have you managed to validate this with a version of `auth0.js` that sets `SameSite` correctly? We haven't produced such a build but just wondering if it was something you had tried.

**Comment by smaclell** [comment]
Thank you for your response.

In our case the code initiating the authentication and validating the response share data. If that is the case why does the state need to be saved to a cookie then retrieved when it could be set and compared against the shared data instead? The value is still non-deterministic and we validate the authentication and response match.

1: In our case the entire application is within an iframe so it can be safely embedded in 3rd party sites.

2: I have not managed to validate this with a version of auth0.js that set SameSite. We are using the library, but not authenticating with Auth0. I did not see SameSite mentioned in the release notes, what version would we need to update to in order to get the change?

**Comment by stevehobbsdev** [comment]
> We have added __tryLocalStorageFirst: true to the WebAuth setup to temporarily work around this issue

I think your answer here is to continue using this flag, as it was mainly implemented for this purpose. I get that it feels a **little** hacky with the property name the way it is, but have no plans to remove it. If that's allowing you to get around your issue, I would continue with that.

> what version would we need to update to in order to get the change?

We don't have such a thing, I was really asking about whether you had managed to modify the SDK locally and set the SameSite attribute yourself, to prove that it fixed your issue. But no, otherwise there have been no modifications needed in order to support SameSite.

**Comment by smaclell** [comment]
That makes sense. Thank you @stevehobbsdev
