### ISSUE TITLE
Signup??

### ISSUE THREAD

**Issue by woeterman94** [auth0/auth0.js#1086]
How can I let a user sign-up with the package? I have 9.12.2 installed. 
Couldn't find anything on the readme page.

**Comment by stevehobbsdev** [comment]
Hi @woeterman94,

Using `WebAuth.authorize`, sign-up is taken care of by the login screen that your users are redirected to. However, you cannot sign up new users using the SDK alone.

Here's an example of what that screen looks like:

![image](https://user-images.githubusercontent.com/766403/76845951-a2150d00-6837-11ea-9f97-0dcd1acbc224.png)

**Comment by woeterman94** [comment]
I get that, but how to redirect users to that sign-up page?

**Comment by stevehobbsdev** [comment]
@woeterman94 apologies for the delay.

If you are using the Classic experience with Lock, you must send a custom parameter in the `authorize` call and then create a custom Lock template to pick up this parameter and configure Lock to show the sign-up page. The custom parameter can be retrieved using `config.extraParams` object. You need to do this because Lock as a hosted login page doesn't support this automatically.

If you're using the New Universal Login experience, you can send `screen_hint: 'signup'` in the authorization call options, which will cause the login page to start at the sign-up screen.

Hope that helps!
