### ISSUE TITLE
Passwordless Send Email

### ISSUE THREAD

**Issue by Ketcap** [auth0/auth0.js#1184]
### Passwordless Send Email

When I'm trying to use function below from auth0 authorization client as api requires. But this function throws error as 

Function Used
```js
authClient.passwordless.sendEmail({
    email,
    send: 'code',
  });
```

I see error is about sending connection as `email` which should be something user pass like database connection for auth0.

### What was the expected behavior?

Receive email with login code.

### Reproduction

```js
const authClient = new AuthenticationClient({
  domain: AUTH0_DOMAIN,
  clientId: AUTH0_CLIENT_ID,
  clientSecret: AUTH0_CLIENT_SECRET,
})

authClient.passwordless.sendEmail({
  email,
  send: 'code',
});
```
See error after calling function.

Error: 

```{"error":"bad.connection","error_description":"Connection does not exist"}```

Error on Auth0 logs

```json
{
  "body": {
    "client_id": "",
    "client_secret": "",
    "send": "code",
    "email": "email@gmail.com",
    "connection": "email"
  },
  "qs": {},
  "error": {
    "message": "Connection does not exist",
    "oauthError": "Connection does not exist",
    "type": "bad.connection",
    "uri": null
  }
}
```
### Environment

-  "auth0": "^2.35.0",
-  no browser needed
-  no library needed

**Comment by Ketcap** [comment]
It can be about passwordless not enabled but i'll keep it open for investigation and better error message for developers.

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @Ketcap. As the error describes, it looks like the `email` connection has not been enabled on the Auth0 client application that you're attempting to log in with. See [Passwordless: Configure the Connection](https://auth0.com/docs/connections/passwordless/guides/email-otp#configure-the-connection) on Auth0 docs.

However, your issue is not for this repository, which is a browser-based JavaScript authentication client for Auth0. I suspect you probably want to raise it on the [node-auth0 repository](https://github.com/auth0/node-auth0) if you are still having trouble.
