### ISSUE TITLE
Logging in with long next URL in state causes large cookies to be set

### ISSUE THREAD

**Issue by jfrag1** [auth0/auth0.js#1263]
### Describe the problem

This isn't so much a bug report, but seeking clarity on cookie setting behavior.  I previously opened a ticket with auth0 support and was told to bring the issue here.

In our application, if a logged-out user tries to access a resource that they must be logged-in to access, we redirect them to the login page, and then redirect them to the resource after they login using the state parameter to store the resource URL. We've noticed that after the login is completed, two cookies get set. The cookies are named com.auth0.auth.next<percent-encoded next URL> and _com.auth0.auth.next<percent-encoded next URL>_compat. The cookie values appear to be json with 3 key/value pairs: nonce, state, and lastUsedConnection.

We recently noticed that if the next URL is excessively long, the cookies that get set are too large and our application responds with a 400 Bad Request - Request Header Or Cookie Too Large from nginx after the user authenticates. The user is entirely blocked from using the application until they delete those 2 cookies. I couldn't find anything in the documentation about them. We'd like to understand whether these cookies are necessary and what approach to take to solve this problem.

### Environment

- **Version of Auth0.js used:** 9.19.0
- **Which browsers have you tested in?** Chrome
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks for raising @jfrag1. Those cookies store transactional data, mainly for ID token verification once your authenticated user is returned to your app. The reason we have two cookies is because one of those is a compatibility measure (the one with the `_compat` suffix) for browsers that do not support the SameSite attribute (as set by the _other_ cookie, which could not be read by such a browser).

As a side note, in the [latest version](https://github.com/auth0/auth0.js/releases/tag/v9.19.0), we added a setting `legacySameSiteCookie` that you can use to turn off this compatibility cookie, if you know you don't need it.

As for your URL, you haven't shared the code you're using to store this but if you're expecting those URLs to be so large that storing them inside this transaction cookie causes a problem, I would look at alternative means to retrieve this URL once your user returns to your app but the solution to that is within the realm of your application, rather than the SDK.
