### ISSUE TITLE
Cross origin verification page return unauthorized on safari

### ISSUE THREAD

**Issue by oknoorap** [auth0/auth0.js#1309]
### Checklist

- [X] The issue can be reproduced in the [auth0-js sample app](https://github.com/auth0/auth0.js/tree/master/example) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0.js#readme) and [Examples](https://github.com/auth0/auth0.js/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0.js/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0.js/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The cross origin verification page is not working, blank empty. I am using Safari  v16.5

### Reproduction

1. I've setup cross origin verification page https://auth0.com/docs/get-started/applications/set-up-cors#create-cross-origin-verification-page
2. After I signed-in using user and password (on my custom page, e.g `https://domain.tld/signin`), It'll be redirected to `auth0domain.tld/authorize`
3. Then Safari is downloading `verify` file, says it's `Unauthorized`, then it's blank, not redirecting to the callback URL
4. The screen remains empty or blank.
5. No logs in auth0 dashboard.

### auth0-js version

9

### Which browsers have you tested in?

Safari

**Comment by stevehobbsdev** [comment]
Hi @oknoorap, unfortunately this particular scenario is not something we are able to support. Cross Origin Authentication requires third-party cookie support to work (see [limitations](https://auth0.com/docs/authenticate/login/cross-origin-authentication#limitations)) and [Safari blocks third-party cookies by default](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/) since 13.1.

Because cookies are blocked in this case, Auth0 can't read them and hence you get `Unauthorized`. Unfortunately there's nothing I can recommend as an alternative if you must use cross-origin authentication with Safari, other than using [Custom Domains](https://auth0.com/docs/customize/custom-domains), which is a paid Auth0 feature.
