### ISSUE TITLE
react native port version?

### ISSUE THREAD

**Issue by joonhocho** [auth0/auth0.js#147]
I want to use this SDK in my react native app, but it seems that it's tied to the browser environment by looking at the source.
Is there a node / react native port of this SDK?

I want to use APIs such as `renewIdToken`, `refreshToken`, `getDelegationToken`, etc.

**Comment by joonhocho** [comment]
same question on stackoverflow.
http://stackoverflow.com/questions/36917653/using-auth0-sdk-in-react-native-app

**Comment by hzalaz** [comment]
@joonhocho I believe it will be easier for you to perform the request using JS `fetch` API since it's just a request to the API. 
This library handles all the hassle of browser and redirect (and cordova) which you won't need, and also we are not planning to port this SDK to RN in the short term.

We have a node library https://github.com/auth0/node-auth0 but in order to work in react native you need to add a couple of modules to polyfill some node dependencies (e.g. Buffer).

**Comment by joonhocho** [comment]
I created a repo https://github.com/joonhocho/auth0-react-native, which is basically a port of this repo without popups and other browser specific APIs.

Differences:
 - `Promise` everywhere. No callbacks. It's for react-native and possibly node. So I assumed that it wouldn't matter.
 - No `cross origin (CORS)` checks. Again, it's for react-native and node. So it shouldn't matter.
 - It uses `es6` with babel. More concise source. Number of lines got almost halfed.

Similarities:
 - Using the same unit test cases. Currently about 60+% are passing.

TODO
 - SSO ? Not sure how this works, and not sure it should be supported on react-native and node environments.
 - Passwordless. Working to get test cases to pass.
 - Documentation. Currently almost no documentation except for test cases. I will link to this repo.

PRs are welcome please help!

**Comment by hzalaz** [comment]
@joonhocho thanks, we are little short on manpower since we are rewriting some of our libraries and Lock ports but if we have some time we'll see what we can do. We'll probably try to make node-auth0 work everywhere so we can keep the # of libs to a minimum but we'll see.
