### ISSUE TITLE
Breaking changes in version 7.0.1

### ISSUE THREAD

**Issue by SomaYarlagadda** [auth0/auth0.js#165]
Hi,

The latest version of auth0.js version: "7.0.1" has some breaking changes. After the update to the latest version the callback functions are not getting invoked after the call to auth.signin or auth.signup. 

For example:

this.auth.signin({
connection: this.authZeroConnection,
popup: false,
sso: false,
responseType: 'token',
authParams: {
scope: 'openid user_metadata'
},
username: this.userName,
password: this.password
},
(profile: string, token: string) => this.saveProfileAndTokenToLocalStorage(profile, token),
(error) => this.notifier.error(this.customMessages.loginFail));
}

In the above code the callbacks, either succes or failure are not getting called after the call to auth.signin. This is functional in 6.8.1 but not in new version.

Thank you,
Soma.

**Comment by gnandretta** [comment]
Hi, the incompatible changes are intentional and we released a major version because of them. They are documented in the [CHANGELOG](https://github.com/auth0/auth0.js/blob/master/CHANGELOG.md#700---2016-05-09). 

Please note that the example code has two callbacks but both versions of auth0.js 6 and 7 only take one. Maybe you are using a wrapper around auth0.js? The following snippet shows how the callbacks should be used.
```js
// v6
auth0.signin(options, function(error, profile, id_token) {  ... });
// v7
auth0.signin(options, function(error, result) {  ... });
```

**Comment by SomaYarlagadda** [comment]
I am using the auth0-angularjs wrapper and it was not working with one call back function for both the success and failure cases.

**Comment by gnandretta** [comment]
This is the repository for _auth0.js_. _auth0-angular_ is another library which hasn't been updated to work with auth0.js v7 yet. You can follow auth0/auth0-angular#263 for any updates on that.
