### ISSUE TITLE
Auth0 login

### ISSUE THREAD

**Issue by thqnhat** [auth0/auth0.js#209]
Hi there,

I had a Regular Web App using ASP.NET MVC 5 and auth0.js v7.0.4.

Here are some codes on the client side to authenticate the user:
```
 var auth0 = new Auth0({
                domain: Login.config.domain,
                clientID: Login.config.clientId,
                callbackURL: Login.config.callbackUrl,
                responseType: 'code'
            });
 auth0.login({
                connection: Login.config.connection,
                username: $('#Email').val(),
                password: $('#Password').val(),
                state: 'ru=' + Login.config.returnUrl
            });
```
When the user logged in successfully, Auth0 redirect to my CallbackURL with a code in the query parameter. It worked fine.

But is there any way to know that the user has logged in successfully or not in this case ? (don't using the callback function in the login).
I used try catch statement wrap around of auth0.login but it does not work.

I would like to know it for display an error message to the user in case of wrong username or password.

Thanks in advanced,
Nhat

**Comment by hzalaz** [comment]
@thqnhat you need to use the callback since auth0.js won't raise an error since it expects a callback. If you are using redirect mode, you can use the `parseHash` function to check if there is a token after auth0 redirects to your page after authentication.

If you need further assistance, please contact us at https://support.auth0.com
