### ISSUE TITLE
Logout v2 is not sending configured client_id by default

### ISSUE THREAD

**Issue by FabienDehopre** [auth0/auth0.js#211]
Auth0.js version 7.2.1

Why does the logout method need an option ```client_id``` when called with ```returnTo``` option since the Auth0 has been instanciated with a client id anyway?

I understand that you can eventually set a ```client_id```explicitly but it could also use the one from the constructor when no ```client_id``` has been provided and a ```returnTo``` is provided.

**Comment by hzalaz** [comment]
@FabienDehopre the API needs that clientId but we are not sending it yet.

**Comment by hzalaz** [comment]
@FabienDehopre after reviewing this, the clientId is not a parameter that is always needed since it's used to validate the url you will return after logout. If you don't provide one, Auth0 will use the account level whitelist and if you specify one the client's whitelist is used instead.

> For more info check our [docs](https://auth0.com/docs/logout#redirect-users-after-logout)

We'll consider a better way for auth0.js to handle this when we tackle the next major version.
