### ISSUE TITLE
Lock redirects to the root of the site when using a React SPA + Social Login

### ISSUE THREAD

**Issue by mikegleasonjr** [auth0/auth0.js#233]
(I know I say "Lock" in the title, but I really thing the bug is in auth0.js)

Steps to reproduce:

I was able to reproduce with my own project AND the the React quick-start project located at: https://github.com/auth0-samples/auth0-react-sample/tree/master/01-Login

Download react project and `npm install`. Don't run the project with `npm start` yet, it will run on the root directory. Instead build it with `npm run build`. Now you can `npm start` to start the server. Navigate to `http://localhost:3000/dist/`. Now the app runs in a subdirectory. Authorize this callback URL in your control panel. Click Facebook login, accept and watch being redirect to `http://localhost:3000/#/home` (notice the /dist/ is gone)

If you use hash routing in a subdirectory (ex.: http://localhost:8000/site/#/), and use Facebook login for example, the callback will come back to http://localhost:8000/site/#access_token=... then the Auth0-js library rewrites the browser URL to http://localhost:8000/#/ (site root). The app still works since there is no real page refresh but if you do refresh yourself, you aren't obviously on your app anymore.

I found out it's auth0-js that rewrites the URL after parsing the access_token from the hash during the callback.

**Comment by mikegleasonjr** [comment]
Well apparently, downloading the zip file embedded with my tokens from the "Clients > Quick Start" page still uses browser hash history while the github repo made a commit "Switch from HashHistory to BrowserHistory	5 days ago". Because...

Switch from HashHistory to BrowserHistory
- `HashHistory` conflicts with Auth0's token redirect mode

So you guys admit there is a problem. Will it be resolved or just hiding it did the trick?

**Comment by hzalaz** [comment]
It's a Lock issue since auth0.js does not modify `window.location.hash` as you can see in the code. We are not hiding it but providing workable samples first until we fix the issue or provide a workaround for the cases where the hash is handled by a framework like a React Router. If you don't agree how the samples is built please send a PR and we'll review it.

We'll update the sample when we release a [workaround](https://github.com/auth0/lock/pull/695) in Lock to avoid cleaning the hash after parsing it
