### ISSUE TITLE
parseHash depends on localStorage

### ISSUE THREAD

**Issue by smaniotto** [auth0/auth0.js#260]
Hi all.

I'm getting errors from users that seem to have localStorage disabled when authenticating via SSO callback.
The error is triggered on `parseHash` method on this line:
```js
var nonce = options.nonce || window.localStorage.getItem('com.auth0.auth.nonce');
```
I'm on version 7.5.0

I'm also using angular-storage, that fallbacks to using cookies when localStorage and sessionStorage are not available.

Not sure if that's a bug or me doing something wrong. Any idea?

Thanks.

**Comment by glena** [comment]
auth0.js attempts to generate a nonce if it is not provided to later verify the token. 

In this case, you will need to generate one manually and provide it in the parseHash options or polyfill it to fallback in angular-storage if localStorage is not available.

**Comment by smaniotto** [comment]
I tried to generate them manually and pass as options on both methods, but it still fails, because it attempts to remove the nonce from localStorage on parseHash:
```js
window.localStorage.removeItem('com.auth0.auth.nonce');
``` 

Also, I don't know if it's a good idea to delegate the nonce generation to the API user. It would be better to have a fallback implemented directly on login and parseHash methods.

As for the authentication functionality itself: having storage enabled should not be a requirement, it becomes a requirement only when I want persistency. Otherwise, the user can submit a login request and get a token that will last for that session only.

What do you think?

**PS**: @glena I saw your #262 and it solves this issue (meaning it doesn't break anymore), but any ideas on avoiding nonce generation by the API user? Maybe using device fingerprint?

**Comment by hzalaz** [comment]
@smaniotto the nonce requirement is to avoid replay attacks of an id_token, and auth0.js will try to generate one for you if you fail to provide one so it's available on the auth result to validate the id_token and discard those tokens without a matching nonce.

It is a good idea to allow the developer to specify a value since he might not finish auth with auth0.js but on server side so he needs to know the nonce value.

With #262 we will avoid the failure if local storage is not available. In that case is responsibility of the developer to generate a nonce if the response_type includes `id_token` on both the login and parseHash calls.

> In v8 we will provide a cookie fallback for the odd case localStorage is unavailable.

Also a nonce should be something better than a device fingerprint since it could be guessable by an attacker. A good way is just generate a random string on each request.

**Comment by smaniotto** [comment]
Yep, got it, I'll just add a workaround until v8 is released and stable. Thanks guys!

**Comment by hzalaz** [comment]
Mitigated by #262, will be ready for v8
