### ISSUE TITLE
Custom UI for Password Reset

### ISSUE THREAD

**Issue by callmekatootie** [auth0/auth0.js#269]
I see that we do have api to reset password: https://github.com/auth0/auth0.js#change-password-database-connections

However, that only sends the email with the password reset link.

1. Is it possible to change the URL to which the password reset link in the email points to? The [documentation](https://auth0.com/docs/connections/database/password-change#customizing-the-change-password-email) seems to suggest that we can only change the redirect URL post verification.
2. Is it possible to have our own reset password UI where the user can enter the new password and api to change the password?

**Comment by hzalaz** [comment]
As you figured out, it's only possible to change the redirect url post verification. For a custom ui you can call this endpoint https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id from your backend but you need to validate your user's old password before.

Please contact ask via https://support.auth0.com for a better guidance since we keep github mostly for library related issues/topics.
