### ISSUE TITLE
Connection behaviour documentation?

### ISSUE THREAD

**Issue by 43081j** [auth0/auth0.js#300]
Currently, if using Auth0 Lock, the form changes depending on username/email input by checking the connections for any matches on key press.

How are we meant to do this through auth0.js directly? In the past, there was a `getConnections()` method but that was mentioned in another issue as being removed.

I tried to follow lock's source to see how it does it (seeing as it uses auth0.js), but no luck seeing as the codebase is so generic/dynamic.

It would be worth documenting this too.

In general, I find the documentation for both auth0.js and lock lacking massively. A quick readme of the common methods and their examples isn't really enough.

[This](https://auth0.com/docs/libraries/auth0js) is more like non-exhaustive list of examples. [This](https://auth0.com/docs/api/authentication) is getting better, but doesn't seem to list every JS method from both libraries. Having the same level of documentation as the API but for both JS libs would be ideal.

**Comment by hzalaz** [comment]
>Currently, if using Auth0 Lock, the form changes depending on username/email input by checking the connections for any matches on key press.
>
> How are we meant to do this through auth0.js directly? In the past, there was a getConnections() method but that was mentioned in another issue as being removed.

This feature is mostly a Lock feature, and you can implement this by listing yourself what domain matches which connection name hardcoding this in your code (without querying Auth0). If you need or want to list the connections I'd recommend listing them using [Management API](https://auth0.com/docs/api/management/v2#!/Connections/get_connections) in your server and relying the necessary info to your fronted since you need admin token to hit that API (this is one of the reasons getConnections was removed in v8)

> In general, I find the documentation for both auth0.js and lock lacking massively. A quick readme of the common methods and their examples isn't really enough.

We know and that's why we have the [quickstarts](https://auth0.com/docs/quickstart/spa) and our support channel https://support.auth0.com since adding all uses of Auth0 in the README is too much and the feature you want to replicate is not asked a lot or common (most people use lock).

> This is more like non-exhaustive list of examples. This is getting better, but doesn't seem to list every JS method from both libraries. Having the same level of documentation as the API but for both JS libs would be ideal.

We are constantly iterating with the docs/quickstarts based on feedback and usage and since we just released v8 we are still building it from scratch.

**Comment by gene1wood** [comment]
@hzalaz How does the Auth0 Lock accomplish dynamically determining the connection list for a given client_id using the management api v2 without a server side component and without hardcoding it?
