### ISSUE TITLE
WebAuth fails to parse a hash in token mode

### ISSUE THREAD

**Issue by mikegleasonjr** [auth0/auth0.js#327]
```
auth0.parseHash(window.localtion.hash, function (err, result) {...});
```

fails and `err` contains `Algorithm HS256 is not supported. (Expected algs: [RS256])`

it is because `parseHash` eventually creates a `IdTokenVerifier` here:
https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L166

and when no `expectedAlg` parameter is specified, it defaults to `RS256`:
https://github.com/auth0/idtoken-verifier/blob/master/src/index.js#L12

versions:

```
├─┬ auth0-lock@10.10.1
│ ├── auth0-js@8.1.2
│ ├── blueimp-md5@2.3.1
│ ├── fbjs@0.3.2
│ ├── idtoken-verifier@1.0.1
│ ├── jsonp@0.2.1
│ ├── password-sheriff@1.0.1
│ ├── superagent@3.3.2
│ ├── trim@0.0.1
│ └── url-join@1.1.0
```

**Comment by mikegleasonjr** [comment]
Great...

I changed to `RS256` in the control panel. Then I had to specify `id_token` as `responseType` for the lock. Not reflected in the docs? https://auth0.com/docs/libraries/lock/v10/customization#responsetype-string-

**Comment by cesarvarela** [comment]
I'm still havint trouble with this

**Comment by hzalaz** [comment]
@cesarvarela can you open a new issue with details about your issue, how to reproduce it, etc?

@mikegleasonjr when using Lock you should not be using auth0.js for resumeAuth, just use Lock's https://github.com/auth0/lock#resumeauthhash-callback. Lock will handle the backwards compat change since auth0.js v8 is a breaking change from v8.

**Comment by mikegleasonjr** [comment]
@hzalaz I migrated thank you
