### ISSUE TITLE
Scope parameter in renewAuth options not having any affect

### ISSUE THREAD

**Issue by garyforsterio** [auth0/auth0.js#332]
When renewing a user's token using the `renewAuth` method, specifying a scope in the options argument different to the one used initially has no impact on the token's claims.

Using auth0.js version 8.1.3.

**Comment by hzalaz** [comment]
@gforster1993 the scope used to call renewAuth should be the same or less than the scopes you originally asked on auth, if you ask for more it should fail since it might require consent from the user.

All this affects the `access_token`, is that what you are talking about or you need to alter the id_token content based on the scope?

**Comment by gforster1993** [comment]
Thank's @hzalaz. Ideally we need to alter the id_token as I'm still unsure how to migrate to `access_token`s. So if we have two clients, both with the Auth0 SSO flag enabled and using Auth0 Lock and the `renewAuth` method from the `auth0.js` library, provided they are given same scope SSO should work? Or does one currently operate on the id_token and the other access_token?

**Comment by luisrudge** [comment]
Hi! Hi'm sorry about the copy/paste message, but we're doing some clean up. 🗑 
It's been a while since you opened this issue. Are you still having this issue with the latest version? If so, please reopen it with some repro steps so we can help!
