### ISSUE TITLE
loginWithCredentials deprecated?

### ISSUE THREAD

**Issue by victorias** [auth0/auth0.js#339]
Is loginWithCredentials planning on to be deprecated? The only deprecation note is when you call it, either directly or via signup, but its not noted on the website to be deprecated. What is the deprecation strategy here?

**Comment by hzalaz** [comment]
There is just a small warning that is going to be deprecated soon and we want new users to start using the other endpoints. Since it's just a warning not a deprecation notice with migration steps is fine to either ignore it or disable the warnings via parameters.

For signup and login we recommend just performing the signup and for login using `client.login`.

**Comment by victorias** [comment]
Thanks for the quick answer. Since signup calls loginWithCredentials, will signup change soon?

**Comment by victorias** [comment]
redirect.signupAndLogin is the one I'm referring to. Should we be using just signup now?

**Comment by hzalaz** [comment]
It's fine to use it as long you don't need API tokens obtained via our OAuth 2.0 features, if you need them you need to use signupAndAuthorize from webAuth, but that does not perform a redirect is just a xhr call.
