### ISSUE TITLE
redirect withLoginCredentials ignoring audience

### ISSUE THREAD

**Issue by mattdodge** [auth0/auth0.js#352]
I would like to use auth0-js (not the lock) to initiate our logins with username/password. I have logins working but the library seems to be ignoring the audience parameter when I make a request. I get a token back but the `aud` value is always my client ID, not the audience I provide. I have set up my audience as an "API" in my Auth0 account and I can get a JWT with that audience when I use the `webAuth.authorize` method, but not when I use the `webAuth.redirect.loginWithCredentials` method. 

Example:
```javascript
var webAuth = new auth0.WebAuth({
  domain: 'mydomain.auth0.com',
  redirectUri: 'http://localhost:3000/example',
  clientID: '<CLIENT_ID>',
  audience: 'https://<MY_API_URL>',
  responseType: 'token id_token'
});
    
webAuth.redirect.loginWithCredentials({
  connection: 'Username-Password-Authentication',
  username: '<USERNAME>',
  password: '<PASSWORD>',
  scope: 'openid'
}, callback);
```

I get a token back but the `aud` value is my CLIENT_ID and not the audience I included in the configuration.

Auth0.js version 8.2.0
Browser/OS: OSX 10.12.3, Chrome 55.0

**Comment by hzalaz** [comment]
@mattdodge `webAuth.redirect.loginWithCredentials` does not support `audience` you need to use `webauth.authorize` or `webauth.client.login`. The former will redirect you to your account login page and the later will perform an XHR and return the requested tokens.

**Comment by controversial** [comment]
@hzalaz Looking at the code in this repository, it seems that [`webAuth.redirect.loginWithCredentials`](https://github.com/auth0/auth0.js/blob/master/src/web-auth/redirect.js#L28-L32) has almost exactly the same code as [`webAuth.login`](https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js#L561-L563), so much so that the latter cannot possibly offer this additional functionality. Since that's the case, I assume you're referring to the `Authentication.login` method defined [here](https://github.com/auth0/auth0.js/blob/master/src/authentication/index.js#L257). Where is there documentation for how to use this function? I couldn't find any.

**Comment by luisrudge** [comment]
@controversial we released a new major version in the past few weeks, so that comment, which is 11 months old now, is not valid anymore. Both `webAuth.login` and `webAuth.redirect.loginWithCredential` should work just fine with the audience parameter.

**Comment by controversial** [comment]
Great! I'll upgrade and give it another try.

**Comment by luisrudge** [comment]
Don’t forget to read the migration guide since there is some configuration changes you might need to do 😬
