### ISSUE TITLE
passwordlessVerify v8 has incorrect validation messages

### ISSUE THREAD

**Issue by lnhrdt** [auth0/auth0.js#354]
When I make a passwordlessVerify call for an `email` connection using v8 and email is not passed, I get the error message for `password`. The tests are also incorrect:

https://github.com/auth0/auth0.js/blob/443d53b2e7cb7f4f10d7b4ad5a06422e4b8c36a2/test/authentication/passwordless.test.js#L133

**Comment by hzalaz** [comment]
I can't see the error message for `password` in the code. The way it validates might prompt you to supply `phoneNumber` all the time if you fail to pass either `email` or `phoneNumber` since it always validates `phoneNumber` first. We'll see if we can rework a bit the message but we'll first complete the documentation.
