### ISSUE TITLE
Alternative to the delegation api endpoint to renew id_token

### ISSUE THREAD

**Issue by mikegleasonjr** [auth0/auth0.js#361]
I am using the `offline_access` scope to get a `refresh_token` along the `id_token`.

I want to use the delegation api to renew the `id_token` using the `refresh_token` but it appears it is deprecated:
https://github.com/auth0/auth0.js/blob/master/src/authentication/index.js#L349

What's the new method? I don't want to use the `renewAuth` non-sense.

**Comment by hzalaz** [comment]
@mikegleasonjr you can still use it since its just says it will be deprecated at one point and the replacement is `renewAuth` so if it works for you we encourage you to use `renewAuth` otherwise using `delegation` for the time being is ok. Once we formally deprecate `delegation` we will provide a schedule and migration path

**Comment by mikegleasonjr** [comment]
I just want to raise my concern that `renewAuth` should not be the sole migration path. We need to have an API endpoint.
