### ISSUE TITLE
webAuth.authorize() is creating a new user automatically

### ISSUE THREAD

**Issue by borgmanz** [auth0/auth0.js#362]
I am using the following:

`webAuth.authorize({
        connection: 'google-oauth2',
        responseType: 'token id_token'
  })`

and even though the authenticated gmail address doesn't have a current User account on auth0, an account is automatically created for them.  Is there any way to have this fail if the user isn't on auth0 yet so I can say, "Please create an account"?  I could just use the user_id of the new account to check my db to see if the user details exist, but I'd rather not then have to delete the User from auth0 if they decide not to create an account.

Thanks.

**Comment by hzalaz** [comment]
@borgmanz sadly no, since calling authorize for a social connection, like google, will create a user in the `google-oauth2` if it does not exist there automatically and it is not store in your database connection (hosted in Auth0 or in your custom DB). I'd suggest contacting us via https://support.auth0.com to get more assistance since what you are trying to do is beyond auth0.js.
