### ISSUE TITLE
Cannot be used from within a class constructor

### ISSUE THREAD

**Issue by lukeshiels** [auth0/auth0.js#407]
__Auth0.js Version__: 8.5.0 (latest as of writing)
__Browser & OS__: _N/A_
__Stack:__ Vue.js built upon Nuxt (don't think this changes anything however)

I'm just getting started using this SDK over Lock however due to my project's requirements I need to use the SDK.

I want to make a class wrapper (with ES6) for this SDK for use within my app, like the following:

![auth0-e-1](https://cloud.githubusercontent.com/assets/11036001/24556455/4f525efc-162c-11e7-86f1-f1996e8e1cc5.jpeg)

However I'm getting the error:
![auth0-e-2](https://cloud.githubusercontent.com/assets/11036001/24556480/6927143a-162c-11e7-96d1-c4b2a7aaf087.jpeg)

I can make an instance of WebAuth fine, it's just when I define it within the 'this' namespace of my class that this fails.

Any ideas/suggestions?

**Comment by luisrudge** [comment]
This is probably related to how nuxt works, since nuxt is trying to serialize your class for whatever reason. I think you have to ask this in the nuxt repo.

Nuxt tries to serialize stuff here: https://github.com/nuxt/nuxt.js/blob/d576dad069b985711a0eca8d0c10c852c0cacec3/lib/render.js#L109
I think the issue is when you server render, it tries to serialize your service or something like that.
