### ISSUE TITLE
delegation removed - no change log entry - no info 

### ISSUE THREAD

**Issue by mwawrusch** [auth0/auth0.js#408]
and the docs say it is not supported with v8?

I need to connect to firebase - now what??

**Comment by hzalaz** [comment]
@mwawrusch since a v8 is a major version and it was a complete rewrite we won't detail exactly in the changeling what was removed.

Also checking in our migration guide https://auth0.com/docs/libraries/auth0js/v8/migration-guide#delegation shows the method to call delegation endpoint (It has a typo we wil fix since the method is in `webAuth.client` instead of `webAuth`) and checking in the source code you can find the method https://github.com/auth0/auth0.js/blob/master/src/authentication/index.js#L401

**Comment by dcorb** [comment]
Typo still there. The delegation method is in webAuth.client
There is very little information how to properly connect to firebase. All examples are deprecated, do you have something more up-to-date?
