### ISSUE TITLE
Broken Google login with Cordova

### ISSUE THREAD

**Issue by lexaurin** [auth0/auth0.js#449]
Since [Google blocks OAuth Requests made via webview](https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/) Google login flow is now broken in auth0.js

I understand that there is an alternative [auth0/auth0-cordova](https://github.com/) which works through Auth0 Hosted Pages but this doesn't help when you actually need to use Auth0 Lock in your app (imported, customized by your runtime needs). There is already issue on this in auth0-cordova lib https://github.com/auth0/auth0-cordova/issues/39 

In our case requirements are [Azure AD multitenant](https://auth0.com/docs/tutorials/building-multi-tenant-saas-applications-with-azure-active-directory) and ability to change Lock look&feel settings according to our application runtime mode. As I understand, this is not possible with auth0-cordova

> - [x] Is this issue something you can fix? Please send us a pull request! Bug fixes are welcome.

Here is the link to our auth0.js fork where we already fixed this for our needs https://github.com/saphocom/auth0.js#readme 

Similar to **auth0-cordova** it uses `cordova-plugin-safariviewcontroller` and also adds Android intent anchor flags to make it work smooth and without losing app state at the end of login flow. 

I will highly appreciate your opinion, advice and help to what else should be done to make it ready for PR to this repo.

**Comment by hzalaz** [comment]
@lexaurin yes its broken but as you said we don't want cordova apps to use this library to authenticate the user and we will put effort in `@auth0/cordova`.

The issue in that repo is not even an issue of a matter of expectative since the customizations should be done in the hosted login page not in the app, if you have multiple apps with multiple logins you must have different clients to achieve a different L&F per app. I know there are some cases not covered by that but  we are going to invest a lot to improve hosted login page customizations.

I saw your fork and overall its ok (I have some concerns about certain hacks in android but we can discuss them later) 
However I would like to follow a different approach than adding those changes in auth0.js since I plan on deprecating the current cordova plugin in favor of `@auth0/cordova`:

- Create a repo for the only plugin code
- publish only that on your own
 -if you want my opinion on the hacks just mention me in  an issue and we can discuss. 

wdyt?

**Comment by lexaurin** [comment]
@hzalaz thanks for the quick answer. I understand your point of view. 

About multiple clients I agree, it solves problem here. But for us, without Azure AD multitenant support it's still useless. If you could support multitenant directly through Auth0 settings it will be a real problem solver.

About Cordova in Auth0.js, I understand that this library is more like plug&play, set and forget, and bundling Cordova support that not everyone need is not a good idea. Especially when it requires specific settings, handlers and plugins. So this can work better as a plugin and that is what first came to my mind when I tried to fix Google login. But there is another problem, plugin system doesn't seem to be public usage ready. I mean, I can live without fancy things like `lock.getAuth().getPluginHandler().getPluginByType(Auth0CordovaPlugin)` but now I even can't set plugin instance on Lock creation because plugin list is not taken from the options but is hardcoded here https://github.com/auth0/lock/blob/master/src/core/web_api/legacy_api.js#L29 or is there another way how to load custom plugin?

So if we can fix plugin propagation, to make possible to set your own plugin like this
```
var lock = new Auth0Lock(clientId, domain, {
  plugins: [new Auth0CordovaPlugin({cordova-specific-settings})]
});
```
I can move fork code to the separate repository and make everything ready on my own. But what with the plugin loading? If you want, I can prepare PR for this too, just tell me what should be done.

**Comment by hzalaz** [comment]
Its easy to add a  config for a plugin in Lock so lets focus on making the plugin work so we can double-check plugin public api so we can add this to Lock too (and avoid breaking changes).

**Comment by hzalaz** [comment]
If you want to make the PR to Lock its also fine. We'd probably discuss internally the plugin system so its ready to be public.

**Comment by lexaurin** [comment]
Finally have time to look at it. Here is PR for plugins propagation https://github.com/auth0/lock/pull/1204 

and our version of Cordova Plugin with SafariViewController and Custom URL Scheme support 
https://github.com/saphocom/auth0-plugin-cordova

Appreciate any feedback
