### ISSUE TITLE
Social (Facebook/Google) Login Popup - language

### ISSUE THREAD

**Issue by rahatjaan** [auth0/auth0.js#454]
I'm using custom UI (and not the Lock) along auth0js for signin/signup. For social login of Facebook and Google users, im using the code below (sample code of Google) and it works very fine.

The only thing i want to have now is to have this facebook/google login popup in a different language, i have gone through the docs but couldn't find any help about how to have multi-lingual facebook/google login popup when using Auth0js.

```javascript
var redirectURL = "/auth0.html";

var auth0 = new Auth0({
    domain: auth0Domain,
    clientID: auth0ClientId,
    responseType: 'token',
    callbackURL: redirectURL
});

auth0.signin({
            popup: true,
            connection: 'google-oauth2',
            display: 'popup'
        },
        function(err, profile, id_token, access_token, state) { //signin response here });
```

**Comment by luisrudge** [comment]
That really depends on the Identity Provider (facebook/google etc). You have to check in your Identity Provider of choice which parameters you need to send that along with the rest of your request. You should also upgrade your version, since you're probably using v7 or older (we're already on v8).
Since this is not a bug with auth0.js itself, I'd suggest you try our [community forums](https://community.auth0.com/) or get in touch with our amazing [support](https://support.auth0.com/) team.
