### ISSUE TITLE
renewAuth returning identity for wrong account

### ISSUE THREAD

**Issue by devpascoe** [auth0/auth0.js#468]
I'm having a strange issue where the renewAuth promise returns an id that is for my social login (facebook) which is a completely different user than the one i originally logged in with (user/pass).
The idTokens are completely different.

I had a snoop around in the auth.js library for how this silent auth is done for accounts with a username/password. Nothing obvious stood out.

My init code ...
```
auth0 = new auth0.WebAuth({
    domain: process.env.AUTH_DOMAIN,
    clientID: process.env.AUTH_CLIENT_ID,
    redirectUri: location.origin + '/callback',
    audience: process.env.AUTH_AUDIENCE,
    responseType: 'token id_token',
    scope: 'openid profile email'
})
```

My user/pass login ...
```
this.auth0.client.login({
    realm: process.env.AUTH_DB,
    username: username,
    password: password,
    scope: 'openid profile email'
}
```

The renew auth code ...
```
this.auth0.renewAuth({
    scope: 'openid profile email',
    redirectUri: location.origin + '/callback-renew',
    usePostMessage: true,
    nonce: 'something something blah blah'
}
```

Then if i go ahead and set my Token Expiration time to say 20 seconds to test on my Auth0 API (that my audience points to) the first 20 seconds are correct. Then when i expire i call renewAuth and the identity returned is from my social login.

My user/pass account has a completely different email to my Facebook account.

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK itself, since we don't control the response of the `renewAuth` call. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario. They'll ask you for a .HAR file so they can track what's going on. If we find that the issue is with auth0.js, I'll reopen this issue and move the discussion here again. Thanks!

**Comment by luisrudge** [comment]
Before you open a ticket though, try to run the same scenario in an incognito/private session.
What I think it's happening in your scenario is that you previously logged in using a social connection and that's the only session Auth0's servers have, since the `client.login` method uses an endpoint that doesn't store sessions at all (you can't use `renewAuth` after `client.login`). If you have to store a session, you have to call `authorize` or use the hosted login page.
