### ISSUE TITLE
Universal Apps need to verify the token on the server side

### ISSUE THREAD

**Issue by JohnCoding94** [auth0/auth0.js#476]
As there are more and more universal applications, i think it is an important feature to be able tu use the lib on the server side.

At least to perform the ``parseHash`` method when invoking the ``/callback``, an univesal app needs to verify the token and to apply to most appropriate redirect on the server side instead of rendering a spinner until the job can be done from the browser.

**Comment by luisrudge** [comment]
Can universal apps hide your auth0 secret effectively?

**Comment by JohnCoding94** [comment]
No, but i don't get the point...
How the ability to perform some tasks on the server side that can be already performed on the client side could be a breaking change in credentials privacy?

**Comment by luisrudge** [comment]
You can decode the token in the client. But, to verify the token, you need auth0's secret (which you can find in the dashboard). If you leak this secret, which will happen if you try to verify the token in a universal app, anyone could issue a token pretending to be your server. So, you can decode, but you can't verify.

So, we try to be universal apps friendly, in a way that we don't blow up when you server render your app. But you shouldn't actively use the library when you're server rendering because we use browser specific code to handle localStorage, redirects, iframes etc. About the token verification, it's just a security vector and we won't compromise in that sense. I hope you understand 🎉

**Comment by sandrinodimattia** [comment]
You should not use the client secret to verify the token. You should use RS256 and use the public key which is a more secure approach (only Auth0 can generate RS256 tokens and both client and server can safely verify these)
