### ISSUE TITLE
Lots of questions, unclear documentation.

### ISSUE THREAD

**Issue by abagshaw** [auth0/auth0.js#599]
Not trying to complain, just hoping to get a few answers and give some feedback.

In general the docs for Auth0's APIs and dashboard/admin panel - and framework specific quickstarts have been super helpful, but it feels like this corner of the platform (auth0.js) has been neglected a little in terms of comprehensive and accurate documentation.

I've spent the whole day just trying to get Cross Origin Authentication working with my existing login ui and the docs seem to be leaving me with more questions than answers...

1. When initializing the `auth0.WebAuth` `responseType` property with just `"token"`, not `"token id_token"` the `id_token` still appears to be returned in the URI (when redirected back). Why is this? Is it not possible to simply request the `access_token` without the `id_token`?

2. The `parseHash()` example [here](https://github.com/auth0/auth0.js#api) includes a separate call to `auth0.client.userInfo()` to get user info after parsing the appropriate tokens from the URL hash fragment. In my tests however, it appears that the `parseHash()` function itself already sends a request to `/userinfo` and includes that information in the `authResult` object passed to the callback as part of the `idTokenPayload` property? Why is it necessary to do another call to the `/userinfo` API endpoint? Isn't this redundant?

3. The github README seems to refer to some functions as callable from instances of an `auth0.WebAuth` object or a `auth0.Authentication` object whereas the docs on auth0.com (see [here](https://auth0.com/docs/libraries/auth0js/v9)) mention nothing about `auth0.Authentication` and seem to call all functions from an instance of `auth0.WebAuth`. What's the difference here? i.e. is `auth0.Authentication({...}).login()` the same as `auth0.WebAuth({...}).login()`?

4. The auth0.com docs highlight [here](https://auth0.com/docs/libraries/auth0js/v9#webauth-login-) that `webAuth.login()` calls the `/co/authenticate` API resource. I can't seem to find documentation on this API resource anywhere...is there a reason for this? Is it not supposed to be called directly?

5. Why does the `auth0.Management` Initialization example [here](https://github.com/auth0/auth0.js#initialize-2) have "YOUR_AUTH0_API_TOKEN" as the `token`? This example is for an untrusted client...right? So why would we provide our Auth0 API Token? Eventually some other example buried somewhere suggested that I use the user's `id_token` instead and that seemed to work for me, but raises some more questions.

6. For the `patchUserMetadata()` method, if we are already passing the `id_token` to authenticate the request why is it necessary to also include the `userId` as a parameter? Presumably that information would be included in the `id_token` payload, no?

I'm sure some of these are silly questions, but I'm having quite a bit of difficulty getting a grasp on this library so I'd thought I'd see if others could help. Thanks very much!

**Comment by luisrudge** [comment]
Thanks for the questions and sorry about the bumps!

1 and 2:
Is your client marked as OIDC conformant in the dashboard? I think non-oidc conformant will always return id_token and, if your token is an HS256 token, we'll always call userInfo to validate the id_token, since HS tokens can't be properly validated. So, if your client is non-oidc, marking it as OIDC will solve 1 and 2.

3: I see no mentions of auth0.authentication in this page: https://auth0.com/docs/libraries/auth0js/v9

4: co/authenticate is an implementation of this RFC: https://github.com/jaredhanson/draft-openid-connect-cross-origin-authentication/blob/master/Draft-1.0.txt#L196 - you could that by yourself,  but that's why we have the sdk, to make the hard parts easy.

5: It's a docs issue. If you read the header, it says it all:
> Provides an API Client for the Auth0 Management API **(only methods meant to be used from the client with the user token)**.

6: yeah, that info is in the token, but we don't want to always decode the token when calling that method. So, instead of doing that, we just expect the userId.

I'll close this issue because we don't have a bug, but feel free to continue the conversation here.
