### ISSUE TITLE
Provide immediate detailed error message on 400

### ISSUE THREAD

**Issue by lorensr** [auth0/auth0.js#605]
During a `checkSession` call, I see this in the browser console:

![image](https://user-images.githubusercontent.com/251288/34376257-da51e6f6-eab8-11e7-8955-dacabe4bc951.png)

And this in the Network tab:

![image](https://user-images.githubusercontent.com/251288/34376307-0d74b752-eab9-11e7-9dd2-75df23d26647.png)

And later on, I get this error in the `checkSession` callback:

![image](https://user-images.githubusercontent.com/251288/34376418-9b4d9ee0-eab9-11e7-918a-b9e7bec4a014.png)

I know I can reduce the timeout, but it would be preferable to immediately (when the 400 response arrives) get a more specific error in the callback.

**Comment by lorensr** [comment]
Also, does the `login_required` error mean that I have to call `.authorize` instead of `.checkSession`? Why?

**Comment by luisrudge** [comment]
how are you calling checkSession? are you using `owp:true`?

**Comment by luisrudge** [comment]
Based on [this](https://github.com/auth0/auth0.js/issues/607#issue-284683005), I assume you're using owp:true in the checkSession call. That's why it's not using the correct response mode. It will start showing the correct errors once you remove it.

It won't show the correct errors if your client's configuration is wrong though (invalid clientId, or lack of web origins configurations) because the server won't be able to verify that we can answer a request via web origins. Other errors will show up accordingly though 🎉
