### ISSUE TITLE
Edge 14 - 16 fails on accessing auth0 tenant

### ISSUE THREAD

**Issue by dilger** [auth0/auth0.js#645]
Hi there,

I am using auth0.js (Version ^9.1.3) to build a custom login page. Everything works fine except on Edge. Whenever I fire my call to log the user in I receive the full authorize url within the browsers address field as it seems like redirecting there. But the browser tells me, that it cannot reach the auth0-tenant.

This is the code I'm using to fire the login:

```
                    this.data.auth0.webAuth.redirect.loginWithCredentials({
                        connection: window.Laravel.auth0.connection,
                        username: this.data.auth0.login.email,
                        password: this.data.auth0.login.password,
                        scope: 'openid email'
                    }, function(err, authResult) {
                        self.loading(false);
                        if (err) {
                            self.data.auth0.errors = err;
                            let code = self.checkErrorCode(err);
                            flashOverlay(self.localize('frontend.overlay.login.errors.auth0.' + code));
                        }
                    });
```

Did anybody else encounter something similar?

Cheers,

Chris

**Comment by luisrudge** [comment]
It's probably some misconfiguration. Can you setup a simple code sample so I can test?

**Comment by luisrudge** [comment]
https://github.com/auth0/auth0.js/blob/master/example/index.html#L257

https://github.com/auth0/auth0.js/blob/master/example/index.html#L301

I just tried this on Edge and it works just fine.

**Comment by dilger** [comment]
Unfortunately the example does work and also locally I could get it to work, but as I am currently testing this also on a password protected site (protected to be only visible to us and our clients) it doesn't work correctly. Appears like it does not allow the authorize url correctly.

As I switched off the password protection temporarily, it worked.

**Comment by luisrudge** [comment]
Here's how things work:

- user enters in your app
- users type login/password
- user clicks the login button
- auth0.js does its magic to authenticate the user based on the credentials
- auth0.js redirects the user to something like: `https://yourdomain.auth0.com/authorize`
- Auth0's authorization server validates the request and then redirects the user to the `redirectUri` parameter that you provided (It's a basic HTTP 302 response)
- the user gets redirected to that url

This is how the protocol works. If there's something in the middle preventing this redirect to happen, you'll have to take a look in that specific part and solve the issue. I'll close this issue because it's not an SDK issue, but feel free to ask more questions if you need to.
