### ISSUE TITLE
Extra fields on signup

### ISSUE THREAD

**Issue by Maxim-Filimonov** [auth0/auth0.js#70]
Hi,
Found during working on https://github.com/auth0/lock/issues/142
I was wondering why it's not possible to pass extra fields in the signUp method? I presume internally it's similar to /users/create api which allows to pass extra fields.

**Comment by rolodato** [comment]
`/dbconnections/signup` is meant to be called client-side. Auth0 has no way currently of knowing what makes up a valid user for each application, other than a valid email and a password that respects the enforced password policy. That is why this endpoint's parameters are restricted to just `email` and `password`. Note that anyone can call `/dbconnections/signup`, while `POST /api/users` requires a client secret to be called. Implementing arbitrary fields on `/dbconnections/signup` would require implementing arbitrary server-side validation logic, possibly with an extended rules mechanism or similar.

This doc describes a custom signup scenario, where the user data is sent to the app server before being sent to Auth0: https://auth0.com/docs/custom-signup

**Comment by Maxim-Filimonov** [comment]
Hm I see haven't thought of server validation for those fields. I would think it's not really a requirement to have validation for those fields. We would validate users profile on our side as I can imagine most of other people will do anyway. The simplest solution could be to have an ability to create a method(similar to the way we create login methods now) which can be used for custom fields validation. `dbConnections/signup`  would just call this method if it exists and pass it custom fields for validation.

The problem I have with the example of custom signup is that it's really simplistic. For example, we gonna be using auth.lock for login functionality with password policies. Now we need to reimplement all this password policies in our custom signup form and keep them in sync somehow. In that case i'd imagine custom signup will lead us to not using auth.lock and not using password policies either and just using auth0 as API only. Which is a valid use case but it's just disappointing to see that we need to do it ONLY because we want to add the name field on the signup form.

**Comment by rolodato** [comment]
> We would validate users profile on our side as I can imagine most of other people will do anyway.

Yes, but allowing clients to call the signup endpoint directly would require validation of all fields in Auth0, not in your application server.

> Now we need to reimplement all this password policies in our custom signup form and keep them in sync somehow

Lock retrieves the password policy configured in the dashboard by downloading a file, [as you can see here](https://github.com/auth0/lock/blob/master/index.js#L178). Then, [password-sheriff](https://github.com/auth0/password-sheriff) is used to provide client-side validation. No need to synchronize dashboard and frontend. We'll likely add this to our custom signup document soon.

Closing this issue for now since it's a discussion about the Auth0 API, not auth0.js. We can discuss further at ask.auth0.com if needed. Thanks for the feedback and suggestions!

**Comment by schickling** [comment]
Any progress on this @rolodato? I was really surprised that a basic feature like this still isn't possible using the library...

**Comment by rolodato** [comment]
@schickling This is already implemented, just send the custom fields under `user_metadata` for a signup call. It's what Lock uses to implement custom fields: https://auth0.com/docs/libraries/lock/v10/customization#additionalsignupfields-array-

**Comment by schickling** [comment]
Thanks for the reply @rolodato. What would be the best way to specify a user's name that it also get recognized for the user's name as mentioned here: https://auth0.com/docs/user-profile/normalized#normalized-user-profile-schema

This is pretty weird...

![](https://i.gyazo.com/e5e949ffe1bfd08f4555c45165676388.gif)

**Comment by rolodato** [comment]
Have you tried sending `user_metadata.name`? In any case there's nothing special about that field, it's not used for anything. The "source of truth" of user profiles is what you see in the Raw JSON tab.

**Comment by schickling** [comment]
Yeah, that's how we do it but as you see in the gif it still produces this buggy behaviour. Also we cannot retrieve the name via the API like if a user would have signed up with Github etc.

I would expect that the name set via `user_metadata.name` gets properly processed as the `name` as described here: https://auth0.com/docs/user-profile/normalized#normalized-user-profile-schema

If that's not the case how do you have to call the parameter in order to make it work? As it is at the moment this just feels buggy...

**Comment by schuchowsky** [comment]
I know this is an old thread, but have you had any luck on this?

I'm also using db-connection, and tried to follow the same documentation as @schickling - about normalized user profile - but no luck so far.

I've tried sending `name` on `user_metadata.name`, or `user_metadata.firstName` and `user_metadata.lastName`, but in both cases, the `name` returned by the api when login in has the `email` of the user - not his name.

This causes an issue for me, because the default user's image is the email's initials, not the user name initials.

**Comment by luisrudge** [comment]
I'm not sure you can set the `name` directly. Please reach out to https://support.auth0.com so they can better answer this specifically. You can set user_metadata.name and just ignore the `name` property in the user returned by the api.

**Comment by schuchowsky** [comment]
@luisrudge no, it's not possible to set `name` directly. But then I've tried using `user_metadata.name`.

It shows correcly in the user list, but not on the raw json / user details. Consequently, the user's default picture is wrong, because has the email initials, not the user name initials.

Please refer to the images:
![](https://d.pr/i/gGidrI+)
![](https://d.pr/i/dft32s+)

I'd like to see `RA` instead of `TE` as the user's image.

**Comment by luisrudge** [comment]
Right. I fully agree with you. This is an inconsistency in the dashboard itself. If you open a ticket, it will be routed to the correct team. Let me know the ticket number and I'll give my 👍 to your issue.

**Comment by schuchowsky** [comment]
I can't open a ticket as we're still using a free account.

I've looked on the community support tho, and found a possible solution: https://community.auth0.com/questions/7480/why-does-a-name-property-in-user-metadata-not-over

Trying it now.

**Comment by yasso1am** [comment]
It seems once a year or so this issue comes back alive. Would love to see this option as currently rolling our own custom auth flow and would like to set the name field as the user who created the gif above so clearly illustrated. Any progress on this? Thanks!

**Comment by luisrudge** [comment]
@yasso1am as of today, you can't set the `name` property directly. best way to give feedback is through https://auth0.com/feedback, which goes directly to our product team.
