### ISSUE TITLE
parseHash: throw a more specific error if id_token.alg===HS256 and access_token is undefined

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#725]

**Comment by mateoholman** [comment]
@luisrudge I'll work on this if no one else currently is!

**Comment by luisrudge** [comment]
@mateoholman that would be amazing, yes 🎉

**Comment by mateoholman** [comment]
@luisrudge It appears you fixed this yourself a month or so after the issue was created 🎉 😄  
PR #727
The error message is pretty solid and the docs were updated with the [new error message](https://auth0.com/docs/errors/libraries/auth0-js/invalid-token#parsing-an-hs256-signed-id-token-without-an-access-token). 
Let me know if there is something I can add to help out, but it appears as if you can close this issue. 🍻

**Comment by luisrudge** [comment]
Wow, I had totally forgot about that. Thanks for the reminder 🎉
