### ISSUE TITLE
Unhandled error when browser does not have sessionStorage support

### ISSUE THREAD

**Issue by MrPrashantT** [auth0/auth0.js#735]
Some user logins will fail with the following error from auth0.js when the browser doesn't support sessionStorage (e.g. old browsers, or IE11 with `Enable DOM storage` disabled).

```
Unable to set property 'co/verifier/<TENANT>/<CODE>' of undefined or null reference
```

Repro steps:

1. Use auth0.js (tested using v9.3.2)
2. Open app in IE11, disable `Enable DOM storage` setting (IE -> Tools -> Options -> Advanced -> Security -> Enable DOM Storage.)
3. Perform cross origin auth using valid credentials, error will be thrown from following line:
https://github.com/auth0/auth0.js/blob/4d352f2daeba74021b341fbadb6c61ae975ccdb5/src/web-auth/cross-origin-authentication.js#L85

Expected behaviour:

Should be handled with a better error message.

More details in ticket: https://auth0.zendesk.com/agent/tickets/37807

**Comment by luisrudge** [comment]
Does `localStorage` works in that case?

**Comment by luisrudge** [comment]
I guess it blocks both.. interesting..  We could use cookies instead, but it would increase the cookie size on every failed authentication request (because we can't clean on failed attempts). I'll have to talk with the team to know if we're going to fix this or not. The internet is pretty much an unusable place without local/session storage...
