### ISSUE TITLE
use of with operator

### ISSUE THREAD

**Issue by andrewgoodchild** [auth0/auth0.js#736]
-------------------------------------------------------------

- [x] Code snippet or sample project that reproduces the bug
- [ ] Screenshots when appropriate
- [ ] Auth0.js version
- [ ] Browser & OS

---------------------------------------------------------------

In some older browsers, like the one embedded in Google Earth, I am seeing a syntax error 'Unexpected token with',  which occurs on line 44 of src/helper/object.js as part of the objectHelper.merge function.

`function merge(object, keys) {
  return {
    base: keys ? pick(object, keys) : object,
    with: function(object2, keys2) {
      object2 = keys2 ? pick(object2, keys2) : object2;
      return extend(this.base, object2);
    }
  };
}`

This function is used in multiple places throughout the code.  Usage of the with operator is not recommended:

    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with

and if your code is running in 'strict' mode it will be treated as deprecated and throw an error:

   http://2ality.com/2011/06/with-statement.html

Prior to the security issue that forced us to update to a newer version of lock this was not a problem, but now we have cut over to universal login and we have to include auth0.js in our build this issue is now a problem.

Is it possible to get the merge function refactored to not use the 'with' operator?

**Comment by luisrudge** [comment]
This is most likely a bug in the browser Google Earth uses. We are not using the "with" operator.

https://github.com/auth0/auth0.js/blob/master/src/helper/object.js#L41-L49

The `merge` function returns an object with has a `with` property, but this is not the same thing as the `with` operator.

**Comment by luisrudge** [comment]
Clarifying after some digging: IT doesn't appear to be a bug, just a really old browser engine. Unquoted reserved words weren't allowed as keys in object literals until ES5, so this browser probably only supports es3 and that's why it's failing.

some links: 
- https://stackoverflow.com/questions/7022397/using-reserved-words-as-property-names-revisited
- http://2ality.com/2015/08/object-literals-es5.html#you-can-use-reserved-words-as-unquoted-property-keys
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

**Comment by andrewgoodchild** [comment]
Thanks for looking into this :+1: 

What you are saying makes sense.
