### ISSUE TITLE
Use new v2/logout endpoint

### ISSUE THREAD

**Issue by rolodato** [auth0/auth0.js#74]
As documented here: https://auth0.com/docs/logout

A `federated` parameter or similar should be added as well.

**Comment by jakuub** [comment]
+1 this would be very helpful, because actual `.logout()` from google account will work like federated and therefore not return to webapp defined in `returnTo` parameter. We fix this by redirect to coresponding by custom code, not by library, but I prefer to use library, if we have it loaded already :-).

**Comment by Haraldson** [comment]
How did you go about redirecting back to the webapp again, @jakuub? Experiencing the same problem with Google on logout.

**Comment by jakuub** [comment]
We finaly didn't use `.logout()` function, but manualy constructed link to v2 logout endpoint link.

**Comment by deviantony** [comment]
Any update on this?

**Comment by johnlim** [comment]
Any reason why it's still not using v2 endpoint? Given that it's a rather straight forward implementation (#112), are we missing something in the grand scheme of things? :)

Thanks.

**Comment by cristiandouce** [comment]
Included in https://github.com/auth0/auth0.js/pull/201
Will be released soon
