### ISSUE TITLE
Improve handling of CORS errors

### ISSUE THREAD

**Issue by danbovey** [auth0/auth0.js#742]
I had a CORS error saying `No 'Access-Control-Allow-Origin' header is present on the requested resource` when calling `changePassword` and it took me a while to troubleshoot. It happens because Allowed Web Origins (in Application settings) doesn't extend Allowed Callback URLs and I never added my URLs to that list in the Auth0 dashboard.

```js
return new Promise((resolve, reject) => {
  auth0_client.changePassword({
    connection: 'Username-Password-Authentication',
    email
  }, (err, resp) => {
    if (err) {
      reject(err);
    } else {
      resolve(resp);
    }
  });
});
```

The `OPTIONS` request that the above function makes doesn't return an allowed origins header so the `POST` request is never made.

Solution: You should catch CORS errors in the library and display a helpful message so that it's easier to debug that the current origin is not listed in Allowed Web Origins. Problem is it returns a 200 response so the only way to catch it is to check if `Access-Control-Allow-Origin` is not present.

- Auth0.js version: 9.4.2
- Browser & OS: Chrome Mac 65

**Comment by luisrudge** [comment]
CORS errors are tricky errors, because when you're offline, you might get a CORS error as well, since the browser can't distinguish both. See [here](https://github.com/visionmedia/superagent/blob/master/lib/client.js#L621). We have amazingn docs that cover when you have to add `Allowed Callback URLs` and that's enough. If you think docs are lacking in this regard, please let us know.

**Comment by luisrudge** [comment]
Added a PR to the docs [here](https://github.com/auth0/docs/pull/6039). Thanks for letting us know!
