### ISSUE TITLE
Requested JWT with HS256 signature, but getting RS256

### ISSUE THREAD

**Issue by mithunshanbhag** [auth0/auth0.js#761]
Via the "advanced section" of my auth0 app settings, I've requested JWTs be signed with HS256. 

![image](https://user-images.githubusercontent.com/2327905/40562548-094d5134-607f-11e8-9e75-7a54815c26de.png)

However when I receive the `id_token` and decode it (via jwt.io) I see that the signature is RS256 (instead of HS256). 

![image](https://user-images.githubusercontent.com/2327905/40562788-0b3e4006-6080-11e8-89dc-4957bc9df4ff.png)

Some additional details: 
 - The `scope` requested is `openid profile` 
 - The `response type` requested is `token id_token`. 
 - This is an Angular (SPA) app making requests via auth0.js sdk.  

Aside: My theory is that the `openid` scope causes the signature to always be RS256.   

Edit: Found some related threads...

- https://community.auth0.com/t/authorization-api-signs-jwts-as-rs256-when-hs256-is-selected/7353

- https://stackoverflow.com/questions/44244970/receiving-hs256-signing-algorithm-instead-of-rs256

**Comment by luisrudge** [comment]
I believe that, because you're using a public client, Auth0 will force using RS256 because HS256 can't store the necessary secrets to validate the id_token. You can read more about this [here](https://auth0.com/docs/applications/application-types#confidential-vs-public-applications). In any case, this is not an SDK issue. If you have any questions about this, please contact support at https://support.auth0.com
