### ISSUE TITLE
URGENT: WebExtension are not supported

### ISSUE THREAD

**Issue by STK913** [auth0/auth0.js#778]
The Legacy Lock API will be removed on July 16th, 2018 and we are forced to switch to the latest version of Auth0 Lock, however it does not support WebExtension.

In the auth0-js/src/helper/object.js class, the getLocationFromUrl method does not support this URL: chrome-extension://inmlkkdpjifbhpujhkaohjihfgfcdlfu
Then, the method returns a null object.

If we modify this method to handle this URL, an exception is generated because redirect_uri=null/index.html.
https://XXX.auth0.com/authorize?client_id=XXX&response_type=token&redirect_uri=null%2Findex.html&state=XXX&scope=openid%20offline_access&realm=Username-Password-Authentication&login_ticket=XXX&response_mode=web_message&prompt=none&auth0Client=XXX

Can you help me please ?
This is urgent because we use auth0 in production and this will directly impact our business.

Environment:
- auth0: "2.9.1"
- auth0-js: "9.6.1"
- auth0-lock: "11.7.2"
- angular: "4.4.3"
- ionic: "3.12.1"
- google chrome: "67.0.3396.87"

**Comment by luisrudge** [comment]
Can you show me how are you using auth0-js? Can you send a PR that makes that method handle an extension url?

**Comment by STK913** [comment]
Hello,

I made available a sample project on Github: https://github.com/STK913/WebExtensionForAuth0

Here is the installation procedure:
- Retrieve the project on Git then configure the Auth0 application in the class Variables.ts (AUTH0_CLIENT_ID / AUTH0_DOMAIN)
- If Ionic is not already installed: npm install -g ionic
- Install packages in the project folder: npm install
- Start the server: ionic serve
- _**http://localhost:8100: the application allows to connect to Auth0 (the "Authenticated" log should appear in the console)**_

- Under Google Chrome, load an unpacked extension (in developer mode): chrome://extensions/
- A new icon should appear in the application bar (Top right)
- Click on it to open the extension and try to connect to Auth0
- _**An exception is generated, which prevents authentication:**_

core.js:1449 ERROR TypeError: Cannot read property 'protocol' of null
    at Object.getOriginFromUrl (object.js:143)
    at WebMessageHandler.run (web-message-handler.js:44)
    at cross-origin-authentication.js:88
    at Request.callback (client.js:611)
    at Request.<anonymous> (client.js:438)
    at Request.Emitter.emit (index.js:133)
    at XMLHttpRequest.xhr.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (client.js:705)
    at XMLHttpRequest.H (polyfills.js:3)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)

**Comment by luisrudge** [comment]
Have you tried using https://github.com/auth0-community/auth0-chrome? This is the recommended way to handle authentication from chrome extensions: https://auth0.com/docs/quickstart/native/chrome/01-login

auth0-chrome uses a simple implementation of PKCE and does everything that Chrome recommends for handling authentication from extensions.

- Chrome WebExtensions / Apps run with native privileges and aren't restricted to user agent restrictions and shouldn't be using intercepts to get the code /token, as it'll lead to the same issues as native apps
- Chrome suggests using chrome.identity namespace for extensions, it also offers a better redirect flow with a url like `https://<appname>.chromiumapps.org/callback` and it'll ensure these requirements are met

The reason behind this change is that chrome extensions are considered Native applications and, because of that, can't use traditional web flows like what you're trying to do.

**Comment by mkotsollaris** [comment]
Now that the repo has been archived, how are we supposed to go around utilizing Auth0 for a Chrome plugin?
