### ISSUE TITLE
Document how to get a refresh token

### ISSUE THREAD

**Issue by lorensr** [auth0/auth0.js#794]
The only mention of it in the v9 docs is to add `offline_access` to `scope`. I did so, but my `auth.authorize` callback object still only has an `accessToken` attribute—no refresh token. 

Alternatively, if I'm supposed to get the refresh token from the server, I can't find anything about it in the [node docs](http://auth0.github.io/node-auth0/).

**Comment by luisrudge** [comment]
what callback object?

If you use `webAuth.authorize({scope: 'offline_access'})`, then you should get the `refresh_token` property in the `redirect_url` like `https://your-redirect.com#refresh_token=FOOBAR`.

**Comment by lorensr** [comment]
Oh sorry, I'm using `auth.popup.authorize`, which has a callback whose second arg is an object

**Comment by luisrudge** [comment]
Do you get the refresh_token if you don't use the popup?

**Comment by lorensr** [comment]
```js
const client = new auth0.WebAuth({
  domain: 'foo.auth0.com',
  clientID: 'bar',
  responseType: 'token',
  audience: 'api.foo.io',
  scope: 'openid profile offline_access foo'
})

const authOptions = {
    connection: 'google-oauth2',
    owp: true,
    popupOptions: { height: 623 }
  }

client.popup.authorize(authOptions, (e, result) => {
  console.log(result)
})
```
logs this:

![image](https://user-images.githubusercontent.com/251288/42481327-d69e6ab2-83af-11e8-93ee-f0847f3e3bdf.png)


I get a blank page with the below error when I switch to `client.authorize()`:

https://foo.auth0.com/login/callback?state=bar

![image](https://user-images.githubusercontent.com/251288/42481223-4331843a-83af-11e8-946b-467717acb211.png)

**Comment by luisrudge** [comment]
for refresh tokens:
- [Our docs](https://auth0.com/docs/tokens/refresh-token/current) mention that this is not supported in [Implicit Grant](https://auth0.com/docs/api-auth/grant/implicit) scenarios.
- You need to enable your [API](https://manage.auth0.com/#/apis) to have offline access
![image](https://user-images.githubusercontent.com/941075/42481593-95684b3a-83b9-11e8-9652-de331fadc055.png)

About the error:
- you should remove owp:true and use a redirectUri instead. [Page example](https://github.com/auth0/auth0.js/blob/master/example/index.html#L333). [Callback example](https://github.com/auth0/auth0.js/blob/master/example/callback_popup.html).

**Comment by lorensr** [comment]
Thanks! I just fixed the setting, and now `offline_access` is included in `result.scope`.

Okay, I don't need to get the refresh token in my SPA—I'm happy to do it on the server. The docs page you linked talked about a `code`, which I don't have—I only have the `accessToken`. Can I send the `accessToken` to the server and use it there to get a refresh token?

**Comment by luisrudge** [comment]
You only get the token because that's what you're asking for: `responseType: 'token'`.
In your case, the best approach is to use the [Authorization Code Grant](https://auth0.com/docs/api-auth/grant/authorization-code), so you'd have to change that to `responseType: 'code'` and redirect to your backend app, then you can request the refresh_token from your backend, which is a secure client and can safely store the token. Does that make sense?

**Comment by luisrudge** [comment]
You shouldn't use both. Just use 'code' and get the `access_token` and `refresh_token` via your backend.

**Comment by lorensr** [comment]
Why not? I have two goals:

1. Get my SPA an access token that it can use to authenticate to my server.
2. Get a refresh token for future use.

**Comment by luisrudge** [comment]
@lorensr if you get the `code`, you can all `oauth/token` to get the tokens you need: https://auth0.com/docs/tokens/access-token#server-to-server-interactions

**Comment by adematte** [comment]
just thought I'd chime in on this. @lorensr if you have an SPA, usually the best way to refresh your token is to perform a silent refresh using prompt:none parameter, sometimes also refered as a silent authentication. This is usually performed in an hidden iframe so that the user doesn't get disturbed when your app refreshes its tokens. I think in this lib this is partly handled by this method: https://auth0.github.io/auth0.js/global.html#renewAuth

storing refresh tokens in an SPA is not a good idea security wise since a web client cannot be trusted.
