### ISSUE TITLE
Passwordless login fails for first login on macOS/iOS Safari

### ISSUE THREAD

**Issue by alexbaulch** [auth0/auth0.js#820]
- [ ] Auth0.js version => 9.7.3
- [ ] Browser & OS => Safari  - macOS 10.13.4/iOS 11.4.1

Hey guys,

I have a React/Redux SPA set up with a custom passwordless login form the utilises auth0.js to handle the generation of the login code. At the moment though every time a user tries to login for the first time in Safari (on either iOS or macOS) they get an error saying `Unable to configure verification page.`.

After a decent amount of hunting through closed issues on here, I came across [this](https://github.com/auth0/auth0.js/issues/756) which seemed to suggest I needed to use a custom domain in order to get it working. Having now implemented the custom domain I am still getting the same issue so am wondering what, if anything, I need to do to get around this issue?

Having read through the issue linked above quite extensively I thought I would add that I also get an issue when using [https://brucke.club](https://brucke.club), albeit a different one to the issue I am experiencing. The logs for a first time login are below:

```
{
 "event": "a0js_parse_hash",
 "arguments": [
  {
   "error": "invalid_request",
   "errorDescription": "No verifier returned from client.",
   "state": "cvTSJ78N1uqn1a65VfOfUM.A.okUri~5"
  },
  null
 ]
}
```

**Comment by luisrudge** [comment]
Hi! This is all because of the ITP (Intelligent Tracking Prevention) system that Apple released. You can read more about this here:

Safari 11:
https://webkit.org/blog/7675/intelligent-tracking-prevention/
https://webkit.org/blog/8142/intelligent-tracking-prevention-1-1/

Safari 12:
https://webkit.org/blog/8311/intelligent-tracking-prevention-2-0/

We and other Identity Providers are in direct talk with Apple about this but, for the current time, there's nothing we can offer you that would make this work 100%, except using the Universal Login Page.

Another workaround for the time being is catching this error and just trying to re-authenticate the user. The experience is not great, but it might work, since the cookies are sent in the second request.

**Comment by chrisyaxley** [comment]
That really is a terrible user experience.

**Comment by marcusletric** [comment]
I have the same issue using LoginAndRedirect method from Auth0-js. Whenever I open a private window then try to log in, the first time redirect happens after authentication the callback URL has error: 
Unable to configure verification page. Subsequent logins working fine... 

Chrome, FF, IE11 and EDGE does not suffer from this.
Any updates on a fix for this?

**Comment by thoean** [comment]
It's not helping resolving this problem, but we worked around this limitation in our library [auth0-sso-login.js](https://github.com/Cimpress-MCP/auth0-sso-login.js). We're avoiding the call to `checkSession` on the first login, but instead parse the hash. We're still using `checkSession` for follow-up checks to keep the user logged in on long website sessions. The related pull request was [PR 36 in auth0-sso-login.js](https://github.com/Cimpress-MCP/auth0-sso-login.js/pull/36).

Again, not a solution to this problem, but hopefully some inspiration on how some applications can work around it.

**Comment by luisrudge** [comment]
Conversations on this topic are still ongoing. A few days ago, we were advised by Apple to build our case in the public tracker for the [Storage Access API Proposal](https://github.com/whatwg/html/issues/3338). We started publicly doing that [3 days ago](https://github.com/whatwg/html/issues/3338#issuecomment-434117847). All future discussions will be made in that thread.

It's important to remember that the Storage Access API thread has nothing to do with ITP itself. Using the new API would be a way to mitigate the effects of ITP.

For now, the only workaround is to use [custom domains](https://auth0.com/docs/custom-domains).

@richardblocksure this issue is closed because this is not a bug, it's limitation that is documented here: https://auth0.com/docs/cross-origin-authentication#limitations-of-cross-origin-authentication

**Comment by richardblocksure** [comment]
Thanks @luisrudge . I will follow and comment (where appropriate ) on the thread you have highlighted. I understand this is frustrating for all parties involved and appreciate your efforts in mitigating the effects. My concern is that other browsers soon follow suit and make the resultant experience unpleasant.
