### ISSUE TITLE
webAuth.popup.authorize is inconsistent with webAuth.authorize

### ISSUE THREAD

**Issue by Pyrolistical** [auth0/auth0.js#836]
auth0.js version 9.8.0

When using `webAuth.popup.authorize`, the callback will have an `authResult.idTokenPayload` with the user profile. The profile will contain `appMetadata`.

When using `webAuth.authorize`, then using `webAuth.parseHash` upon the redirect, the callback will have an `authResult.idTokenPayload` with the user profile. The profile will contain `app_metadata`.

This is very confusing by switching between redirect and popup causes the profile to be camel cased or not. This does not only apply to app_metadata, it applies to all fields on the profile.

This is especially annoying when using email/password database as that must be redirect only and if we use social login as pop, we need handle both form of casing.

**Comment by mariosant** [comment]
The same applies for `webAuth.checkSession` as well. This is because of using the following as a convention:
https://github.com/auth0/auth0.js/blob/master/src/helper/response-handler.js#L79

This feels like an early design issue - people were not sure how they should serve/handle stuff, which lead to such inconsistencies. I am curious, how should this one be fixed?

**Comment by luisrudge** [comment]
This will be a hard one to solve without a breaking change 🤔

I'll add this to my near term backlog so I can take a deep look.
