### ISSUE TITLE
don't use cookies inside the HLP

### ISSUE THREAD

**Issue by luisrudge** [auth0/auth0.js#882]

**Comment by nicosabena** [comment]
I'll chime in here since I brought this up. Rather than don't use cookies, we should rather ditch the `transactionManager` usage altogether when doing work on the HLP.
The `transactionManager` generates, stores and retrieves the `state`, `nonce`, `appState` for authorization requests started from an SPA, so that Auth0.js can validate the response when processing the callback. But the HLP itself does not do any of this (the internal state is generated and validated by the server), so we can take all this out when Auth0.js is used in the HLP.

**Comment by cocojoe** [comment]
Thanks @nicosabena

**Comment by nicosabena** [comment]
https://github.com/auth0/auth0.js/commit/9b2a98f9552a1fa845c431ffbeb3a326399f9eca in #889 only addressed this partially, for the `login` function in `webAuth`. But this is still an issue for other uses: `authorize()` and all the passwordless methods.
