### ISSUE TITLE
Safari produces invalid_token error on login

### ISSUE THREAD

**Issue by beno** [auth0/auth0.js#894]
- [ ] Code snippet or sample project that reproduces the bug

https://carnext.cloud 
People on Safari can not login there. Auth0 gives back an error:

{error: "invalid_token", errorDescription: "Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."}

This is the code that gets run on the client. On Chrome it all works flawlessly.

    class Auth
      constructor: ()->
        @auth0 = new auth0.WebAuth
          domain: 'xxx.eu.auth0.com',
          clientID: 'xxxxxx',
          responseType: 'token id_token',
          scope: 'openid profile',
          redirectUri: window.location.origin

    authenticate: ->
       @auth0.authorize()

- [ ] Auth0.js version

Happens on both auth0-js 9.8.2 & 9.9.0

- [ ] Browser & OS
 
Safari 12.0.2, Mac 0.14.2 (

Make sure to include **as much information as possible** for us to understand and reproduce the bug, that way we can fix it as quickly as possible.

**Comment by luisrudge** [comment]
This URL is returning a 404 for me. The error your mentioned is a network error. Are you using any extensions etc?

**Comment by beno** [comment]
Hi, thanks for your reply, yes we were making some changes, back up now.

I initially slightly misrepresented the issue (I overlooked that we are suppressing the console message ourselves), but on GitHub it is now accurately worded.

I have seen quite a bit of similar discussions, and am now under the impression we need (paid) Custom Domains turned on to make this work reliably in Safari?

Thanks for your help,
Michel

**Comment by luisrudge** [comment]
Safari only shows issues when you want to refresh a token (silent authentication) because that runs on an iframe. Standard authentication should work correctly.

You'll want custom domains if you want to refresh a token from your website (to extend a session, for example).

In any case, since this is not an SDK issue, please contact support at https://support.auth0.com with a HAR file so they can better assist you.

**Comment by luisrudge** [comment]
Can you send me the HAR File?

Luís

________________________________
De: beno <notifications@github.com>
Enviado: quinta-feira, janeiro 17, 2019 12:26 PM
Para: auth0/auth0.js
Cc: Luís Rudge; State change
Assunto: Re: [auth0/auth0.js] Safari produces invalid_token error on login (#894)


I can't really say what kind of issue it is, but on the support site it has been suggested to continue the discussion here. This is a huge problem for us and I have no idea how to fix it. Please help.

**Comment by beno** [comment]
Great, it is In your mail

**Comment by luisrudge** [comment]
Did you check the `Preserve Log` checkbox? I’m only seeing a subset of requests. I need you to record the HAR file from the moment you hit `carnext.cloud` until auth0 redirects you back to your application.

I tested this myself and I'm seeing this request is failing:
![image](https://user-images.githubusercontent.com/941075/51331006-db998f00-1a5f-11e9-8b10-22a24c455774.png)

> https://carnext-3p.eu.auth0.com/.well-known/jwks.json

That's why you're getting this error.

- Did you setup CORS in your client correctly?
- Maybe your policies are blocking this request in safari?
![image](https://user-images.githubusercontent.com/941075/51333762-96785b80-1a65-11e9-86b3-45cc8b3e782e.png)

**Comment by beno** [comment]
Well I can’t open the inspector on an new private window, so the Recording is from when I click the login button until the error. I haven’t made any client changes or set any other policies. I can login with the same Safari browser just fine using the 01-Login example code, and we use nearly identical code. 

BTW, the carnext.cloud app is not in production so feel free to play around with it and reproduce the error yourself. 

I will retry the HAR recording later tonight. 

Thanks,
Michel

**Comment by luisrudge** [comment]
The headers I just sent you come from your application. Those policies are blocking the jwks url and causing the parseHash method to fail.

![image](https://user-images.githubusercontent.com/941075/51336276-43a1a280-1a6b-11e9-900e-1185f7524d7e.png)

**Comment by beno** [comment]
OK , thanks a lot, these are the defaults for an Elixir/Phoenix app so maybe something to address in the docs or error message?

I hate to take any more of your time, but could you point out which settings specifically are the culprit and what they should be?

In any case, thank you very much for your trouble and for pointing me in the right direction.

Brgds,
Michel

**Comment by luisrudge** [comment]
There's nothing we can do in the SDK to prevent or improve the error message. The code can't differentiate between a failed request and a request that the Browser decided to block because of a policy.

I don't know how the policies work in general, but I'd say that cross-origin-window-policy and x-permitted-cross-domain-policies might be a good start. Also, if you use CNAME, this problem might go away entirely, since it wouldn't be a cross-origin request anymore.

**Comment by beno** [comment]
Well I removed all security headers from the response, but alas, the error remains. One very weird thing is that now every once in a while it does pass (after some reloads), but mostly it errors out exactly the same as before. What am I doing wrong. I put the unsecured config online so you can take a look. 

And I was so sure we were there. This is really starting to wear me out.

**Comment by luisrudge** [comment]
I tested and got a weird redirect loop in chrome.. it only works in the second or third time. Safari never works.. 

I'm under the impression this is a server configuration issue, specially since you said the 01-login example works, but I can't pin point what it is. I sent a message to our backend team so they can figure this out.

> I can login with the same Safari browser just fine using the 01-Login example code

Did you use the same tenant/client for this test?

**Comment by beno** [comment]
Yes all the same browsers on the same machine. Only difference is the server platform (node vs phoenix). I reverted some small experiments so the redirects etc should be back to normal.

**Comment by beno** [comment]
It gets weirder and weirder, because when I do that and largely copy over the contents from 01-Login it all works fine (of course). So it is not Phoenix and those security headers are not the problem. So now I am thinking it is my Javascript-fu, since I made a slight rewrite and converted it to coffeescript. I will now move from the working code ( https://github.com/beno/auth0bug <https://github.com/beno/auth0bug>) to what produces the bug and see where it breaks. Sorry for calling it Auth0bug since it most likely is not that :)


Michel

**Comment by luisrudge** [comment]
is this repo private? I'm getting a 404

**Comment by beno** [comment]
Welp how did that happen? Made it public now.

**Comment by beno** [comment]
So the gist of it is that I added these lines:

     handleAuthentication();
       if (isAuthenticated()) {
        // Start App...
       } else {
         webAuth.authorize();
       }

which gives the error, and I can get rid of it by adding a timeout.

     handleAuthentication();
       if (isAuthenticated()) {
        // Start App...
       } else {
        setTimeout(webAuth.authorize, 1000)
       }

This has got be the wildest bug hunts I have ever been on, but at least you have something to go on. I can't believe this has never happened before, I think my use case is pretty common? Anyway, thanks for your help and best of luck.

**Comment by beno** [comment]
Some more thoughts:  it appears `isAuthenticated` needs a while to produce the correct answer? After login and `handleAuthentication` is called,  `isAuthenticated` is still false, and this is where things start breaking down. I thought `handleAuthentication` was a normal, inline function, but it seems it has some network delay or something. Very strange, but I will implement it with callbacks so we get rid of this behaviour. Thanks again.

**Comment by beno** [comment]
@luisrudge Curious to hear your take on this?

**Comment by luisrudge** [comment]
Ops, sorry. I missed your last update. I'll come back to this today.

**Comment by luisrudge** [comment]
So, yeah... `handleAuthentication` is async because it calls `parseHash`, which is an async call and accepts a callback. In your case, the best way to handle this is add a callback to `handleAuthentication`.

```js
handleAuthentication(function(err) {
  if (err || !isAuthenticated()) {
    webAuth.authorize();
  } else {
    console.log('Start App...');
  }
});

```

**Comment by andreasvirkus** [comment]
Note @beno to make this work you should wrap `webAuth.parseHash()` in a Promise and resolve it in `parseHash`'s callback, that way your code will know when `handleAuthentication` has finished.
