### ISSUE TITLE
Import fails on node.js because window is not defined

### ISSUE THREAD

**Issue by tpbowden** [auth0/auth0.js#959]
### Description

`import auth0 from "auth0-js";` causes an exception on nodejs

### Prerequisites

- [x] I have checked the [documentation for this library](https://auth0.github.io/auth0.js/index.html).

- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.

- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/auth0.js/issues) and [PRs](https://github.com/auth0/auth0.js/pulls).

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Environment

Please provide the following:

- Version of Auth0.js used: 9.11.1
- Browser and OS version(s) affected: Any nodejs
- Additional libraries or browser extensions being used that might affect behavior: N/A

### Reproduction

```
$ yarn add auth0-js
$ node
> const auth0 = require("auth0-js");
```

Output: 

```
Thrown:
ReferenceError: window is not defined
```

**Comment by luisrudge** [comment]
This library is not meant to be used in nodejs. Checkout https://github.com/auth0/node-auth0

**Comment by tpbowden** [comment]
@luisrudge I appreciate that, but we are trying to use this library in a server rendered React app. While we load this library on the server, none of the functions which rely on browser functionality are called. Is there a way you could just make it possible to import the library on the server, similar to how 9.10.x works?

**Comment by luisrudge** [comment]
When the lib is initialized, it checks to see if localStorage is available or not, that's why we need the window object. Normally, when you're SSRing your app (like using Next.js, for example), you're better off avoiding using Auth0.js altogether. We have a great write up on this here: https://auth0.com/blog/next-js-authentication-tutorial/

**Comment by tpbowden** [comment]
Thanks, I'll have a read of that

**Comment by bkniffler** [comment]
I think this is an issue with `auth0-js`. 

First of all, this problem has been recently introduced, since 9.10.4 works great, 9.11.x causes my builds to break. When using `^9.10.4`, 9.11.x will be installed automatically. So if no lock file used, builds will break.

Second, it really is not hard to check for window to exist (typeof window !== 'undefined'). 

Third, there is valid reasons to use auth0-js in server rendered apps. Cases where you may for example show a placeholder in your sidebar and then, on client side, if user is logged in, render the avatar image. The whole stuff that is user specific can easily be lazy loaded on the client side after initial render.

**Comment by tpbowden** [comment]
Agreed. At the very least this should have been a major version bump

**Comment by luisrudge** [comment]
Can you give me a stack trace on where the error is happening?

**Comment by tpbowden** [comment]
@luisrudge I can't give a helpful stacktrace as everything is minified, but the error is originating in the `unfetch` package. 

My guess is that you're packaging `isomorphic-unfetch` along with `idtoken-verifier`, which means only the web version will be included in the final bundle.

**Comment by luisrudge** [comment]
I think `isomorphic-unfetch` is doing what it is supposed to do, as are we. This is a browser-only library, so it makes sense to package the library as we do. If you're SSRing your app, you need to make sure that you're loading our library only in the client side. For example, Next.js has a way to disable SSR for dynamic imports: https://github.com/zeit/next.js#with-no-ssr.

**Comment by bkniffler** [comment]
NextJS has dynamic imports, but these are (in nextjs context) meant for component rendering, not for utility libraries.

I would really expect a library like auth0-js to work without throwing exceptions if imported. I totally get we can't actually use auth0-js on the server (which auth0-node is for). There is many solutions, like modifying next.config.js/webpack config to alias auth0-js to some noop library server side or whatever. But if I had to do such efforts for each of the libraries I'm using through my apps, I'd be writing a lot of config code.

I'm still considering this a bug since previous versions worked without throwing, and as I said, the reason I came aware of this issue was failing builds (on my CI environment), so now I (and I'm sure others, lets wait and see) will have to invest time fixing this by doing stuff like:

```
let auth0;
if (typeof window !== 'undefined') {
auth0 = require('auth0-js');
}
```

The wonderful typescript bindings, of course, will not work now. But well, at least no exception.

**Comment by bkniffler** [comment]
Here a reproduction btw:
https://github.com/bkniffler/auth0-bug

**Comment by luisrudge** [comment]
I had a nice conversation with @timneutkens and @developit and they helped me finding a solution for this. We'll fix this in the next release: https://github.com/auth0/idtoken-verifier/pull/42

Thanks for your patience 🎉

**Comment by H3RSKO** [comment]
I'm still having this issue. 

auth0-js v.9.11.1 is not updating its idtoken-verifier dependency to v.1.4.1 in yarn.lock

I'm using Yarn and have not been able to selectively update the dependency. This seems to be a known bug (https://github.com/yarnpkg/yarn/issues/4986) with several workarounds, but none of them have worked for me.

I'm still getting the "window is not defined error." Any ideas?

**Comment by luisrudge** [comment]
We’ll release a new version on Monday.

**Comment by dgilling** [comment]
Why is this issue closed without resolution? We ran into the same problem on what was expected to be just a minor version bump with no breaking changes. Our web app is also an isomorphic react app.

**Comment by luisrudge** [comment]
@dgilling there was no breaking changes for our supported scenarios. As said in https://github.com/auth0/auth0.js/issues/959#issuecomment-511030335, we'll release a fix for this next Monday.

**Comment by dgilling** [comment]
@luisrudge Can you consider making Server Side React apps a supported scenario? It's one of the most popular front end frameworks used by startups to companies like Walmart. I am surprised Auth0 doesn't consider this a common scenario and doesn't have regression testing for it.

**Comment by luisrudge** [comment]
It is common, but using auth0.js inside nodejs is not supported (which is what an SSR app does when it's rendering in the server), so it makes sense to keep repeating *this scenario* is not supported. Of course, we want to support your client side part of the app as good as we possible can and we're committed to that. This will be fixed in the next release, which will be out next week.

**Comment by luisrudge** [comment]
Hi everyone. This was fixed in the latest version. Thanks for your patience 🎉 


```js
import { useEffect } from "react";
import { WebAuth } from "auth0-js";

function Home() {
  useEffect(() => {
    const auth = new WebAuth({
      domain: "test.auth0.com",
      clientID: "alsdhalskhd02h0"
    });
  }, []);
  return <div>Welcome to Next.js!</div>;
}

export default Home;
```

**Comment by H3RSKO** [comment]
Working now. Thanks!!

**Comment by GarryOne** [comment]
I got it now using the latest version `9.22.1`

```
/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/auth0-js/src/helper/window.js:12
  return window;
  ^
ReferenceError: window is not defined
    at Object.getWindow (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/auth0-js/src/helper/window.js:12:3)
    at WebAuth.parseHash (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/auth0-js/src/web-auth/index.js:253:22)
    at WebsocketsGateway.handleConnection (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/src/modules/websockets/websockets.gateway.ts:49:34)
    at Object.next (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/@nestjs/websockets/web-sockets-controller.js:77:47)
    at ConsumerObserver.next (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at SafeSubscriber.Subscriber.next (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/rxjs/src/internal/operators/distinctUntilChanged.ts:173:22
    at OperatorSubscriber._this._next (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/mac/www/adrenaline/adrenaline-docker-compose/websocket/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
```

**Comment by frederikprijck** [comment]
Can you elaborate on the use-case to use auth0.js with nestjs @GarryOne ? It looks like you are trying to parse the URL hash on the server, while that shouldnt happen. Instead you should call that method from the client.

**Comment by GarryOne** [comment]
@frederikprijck got it. I was using this library wrongly on the backend.
